# Generated by Django 5.2.6 on 2026-06-12 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_name', models.CharField(db_index=True, max_length=100)),
                ('Recipe_description', models.TextField()),
                ('Recipe_image', models.ImageField(upload_to='Receipes/')),
                ('Recipe_slug', models.SlugField(unique=True)),
                ('Recipe_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Nom-Veg')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ingredients_name', models.CharField(max_length=100)),
                ('Recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipe_ingredients', to='recipes.recipe')),
            ],
        ),
    ]
