# Generated by Django 5.2.6 on 2026-06-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipe',
            new_name='Recipe_home',
        ),
    ]
