# Generated by Django 5.2.6 on 2026-06-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_recipe_recipe_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_home',
            name='Recipe_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
