# Generated by Django 5.2.6 on 2026-07-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_home',
            name='Recipe_type',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=100),
        ),
    ]
